import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  ArrowRightLeft,
  ArrowUpDown,
  CalendarClock,
  CalendarDays,
  Code2,
  Columns3,
  Combine,
  Copy,
  Dices,
  Download,
  Eraser,
  EyeOff,
  FileJson,
  FileSpreadsheet,
  Filter,
  Fingerprint,
  FunctionSquare,
  GitMerge,
  Layers,
  LayoutGrid,
  LineChart,
  Link2,
  ListEnd,
  ListOrdered,
  MoveHorizontal,
  PaintBucket,
  RefreshCw,
  ScanSearch,
  Scissors,
  ShieldCheck,
  Sparkles,
  SplitSquareHorizontal,
  Table2,
  Tags,
  TextCursorInput,
  Trash2,
  Type,
  UnfoldVertical,
  WholeWord,
  Wrench,
} from 'lucide-react';

import type { NodeType } from '@/lib/types';

export const NODE_ICONS: Record<NodeType, LucideIcon> = {
  'source.csv': FileSpreadsheet,
  'source.json': FileJson,
  'source.parquet': Table2,
  filter: Filter,
  select: Columns3,
  rename: TextCursorInput,
  derive: FunctionSquare,
  sort: ArrowUpDown,
  groupby: Layers,
  join: GitMerge,
  concat: Combine,
  dropna: Eraser,
  fillna: PaintBucket,
  cast: Type,
  'output.csv': Download,
  'output.json': Download,
  'output.parquet': Download,
  sample: Dices,
  dedup: Fingerprint,
  limit: ListEnd,
  reorder: MoveHorizontal,
  drop: Trash2,
  'split.column': SplitSquareHorizontal,
  'merge.columns': Link2,
  impute: Wrench,
  pivot: LayoutGrid,
  melt: UnfoldVertical,
  'merge.update': RefreshCw,
  'str.transform': WholeWord,
  'str.extract': ScanSearch,
  'str.split': Scissors,
  'dt.extract': CalendarDays,
  'dt.calc': CalendarClock,
  validate: ShieldCheck,
  outliers: Activity,
  'find.duplicates': Copy,
  'window.rolling': LineChart,
  'window.rank': ListOrdered,
  'window.shift': ArrowRightLeft,
  'ai.classify': Tags,
  'ai.summarize': Sparkles,
  'ai.anonymize': EyeOff,
  'custom.python': Code2,
};

export function getNodeIcon(type: NodeType): LucideIcon {
  return NODE_ICONS[type];
}
